import type { JobPosting } from './types';

export const jobPostings: JobPosting[] = [
  {
    id: 'jp-001',
    slug: 'combined-graduate-level-examination-2026',
    title: 'Combined Graduate Level Examination 2026',
    organization: 'Staff Selection Commission',
    department: 'ssc',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 12450,
    salaryMin: 44900,
    salaryMax: 142400,
    applicationStart: '2026-08-10',
    applicationEnd: '2026-10-15',
    examDate: '2026-11-20',
    status: 'open',
    postedDate: '2026-09-05',
    description: 'Combined Graduate Level Examination for various Group B and C posts across central government departments.',
  },
  {
    id: 'jp-002',
    slug: 'assistant-loco-pilot-railway',
    title: 'Assistant Loco Pilot',
    organization: 'Indian Railways',
    department: 'railway',
    qualification: 'iti',
    discipline: 'ITI in relevant trade',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 9900,
    salaryMin: 19900,
    salaryMax: 63200,
    applicationStart: '2026-08-01',
    applicationEnd: '2026-09-20',
    examDate: '2026-10-15',
    status: 'open',
    postedDate: '2026-09-01',
    description: 'Recruitment for Assistant Loco Pilot positions across various railway zones. ITI or 10th pass with required trade certification.',
  },
  {
    id: 'jp-003',
    slug: 'sub-inspector-executive-capf',
    title: 'Sub-Inspector (Executive)',
    organization: 'Central Armed Police Forces',
    department: 'police',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 1500,
    salaryMin: 35400,
    salaryMax: 112400,
    applicationStart: '2026-07-20',
    applicationEnd: '2026-09-10',
    examDate: '2026-10-05',
    status: 'closing-soon',
    postedDate: '2026-08-15',
    description: 'Sub-Inspector recruitment for Central Armed Police Forces including BSF, CRPF, ITBP and SSB.',
  },
  {
    id: 'jp-004',
    slug: 'probationary-officer-banking',
    title: 'Probationary Officer',
    organization: 'National Banking Services',
    department: 'banking',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 3500,
    salaryMin: 23700,
    salaryMax: 42020,
    applicationStart: '2026-08-15',
    applicationEnd: '2026-10-05',
    examDate: '2026-10-22',
    status: 'open',
    postedDate: '2026-09-03',
    description: 'Probationary Officer recruitment across participating public sector banks. Graduate in any discipline.',
  },
  {
    id: 'jp-005',
    slug: 'primary-teacher-state-education',
    title: 'Primary Teacher',
    organization: 'State Education Board',
    department: 'teaching',
    qualification: '12th-pass',
    discipline: 'D.El.Ed / B.Ed',
    state: 'uttar-pradesh',
    location: 'Uttar Pradesh',
    jobType: 'permanent',
    vacancies: 12000,
    salaryMin: 25500,
    salaryMax: 81100,
    applicationStart: '2026-08-20',
    applicationEnd: '2026-09-30',
    examDate: '2026-11-10',
    status: 'open',
    postedDate: '2026-09-04',
    description: 'Primary Teacher recruitment for government primary schools. 12th pass with D.El.Ed or B.Ed qualification.',
  },
  {
    id: 'jp-006',
    slug: 'junior-engineer-civil-pwd',
    title: 'Junior Engineer (Civil)',
    organization: 'Public Works Department',
    department: 'state-government',
    qualification: 'diploma',
    discipline: 'Civil Engineering',
    state: 'madhya-pradesh',
    location: 'Madhya Pradesh',
    jobType: 'permanent',
    vacancies: 420,
    salaryMin: 35400,
    salaryMax: 112400,
    applicationStart: '2026-08-10',
    applicationEnd: '2026-09-25',
    examDate: '2026-10-18',
    status: 'open',
    postedDate: '2026-09-02',
    description: 'Junior Engineer (Civil) recruitment for Public Works Department. Diploma or Degree in Civil Engineering required.',
  },
  {
    id: 'jp-007',
    slug: 'stenographer-grade-c-ssc',
    title: 'Stenographer Grade-C',
    organization: 'Staff Selection Commission',
    department: 'ssc',
    qualification: '12th-pass',
    discipline: 'Any Stream',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 200,
    salaryMin: 25500,
    salaryMax: 81100,
    applicationStart: '2026-09-10',
    applicationEnd: '2026-10-15',
    examDate: null,
    status: 'upcoming',
    postedDate: '2026-09-05',
    description: 'Stenographer Grade-C and Grade-D recruitment through SSC. 12th pass with stenography skills.',
  },
  {
    id: 'jp-008',
    slug: 'constable-gd-capf',
    title: 'Constable (GD)',
    organization: 'Central Armed Police Forces',
    department: 'defence',
    qualification: '10th-pass',
    discipline: '—',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 5400,
    salaryMin: 21700,
    salaryMax: 69100,
    applicationStart: '2026-07-15',
    applicationEnd: '2026-09-12',
    examDate: '2026-10-08',
    status: 'closing-soon',
    postedDate: '2026-08-12',
    description: 'Constable (General Duty) recruitment for various Central Armed Police Forces. 10th pass required.',
  },
  {
    id: 'jp-009',
    slug: 'data-entry-operator-ssc',
    title: 'Data Entry Operator',
    organization: 'Staff Selection Commission',
    department: 'ssc',
    qualification: '12th-pass',
    discipline: 'Any Stream',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 850,
    salaryMin: 19900,
    salaryMax: 63200,
    applicationStart: '2026-07-25',
    applicationEnd: '2026-09-09',
    examDate: '2026-10-12',
    status: 'closing-soon',
    postedDate: '2026-08-10',
    description: 'Data Entry Operator recruitment through SSC. 12th pass with typing speed requirements.',
  },
  {
    id: 'jp-010',
    slug: 'assistant-typist-state-secretariat',
    title: 'Assistant Typist',
    organization: 'State Government Secretariat',
    department: 'state-government',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'rajasthan',
    location: 'Rajasthan',
    jobType: 'permanent',
    vacancies: 320,
    salaryMin: 25500,
    salaryMax: 81100,
    applicationStart: '2026-07-10',
    applicationEnd: '2026-09-08',
    examDate: '2026-10-20',
    status: 'closing-soon',
    postedDate: '2026-08-08',
    description: 'Assistant Typist recruitment for State Government Secretariat. Graduate with typing proficiency.',
  },
  {
    id: 'jp-011',
    slug: 'clerk-cum-typist-banking',
    title: 'Clerk-Cum-Typist',
    organization: 'National Banking Services',
    department: 'banking',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 1200,
    salaryMin: 19900,
    salaryMax: 63200,
    applicationStart: '2026-07-05',
    applicationEnd: '2026-09-07',
    examDate: '2026-10-15',
    status: 'closing-soon',
    postedDate: '2026-08-05',
    description: 'Clerk-Cum-Typist recruitment across participating banks. Graduate with typing skills.',
  },
  {
    id: 'jp-012',
    slug: 'technical-assistant-pwd',
    title: 'Technical Assistant',
    organization: 'Public Works Department',
    department: 'state-government',
    qualification: 'diploma',
    discipline: 'Engineering',
    state: 'maharashtra',
    location: 'Maharashtra',
    jobType: 'contract',
    vacancies: 180,
    salaryMin: 25500,
    salaryMax: 81100,
    applicationStart: '2026-07-20',
    applicationEnd: '2026-09-11',
    examDate: null,
    status: 'closing-soon',
    postedDate: '2026-08-14',
    description: 'Technical Assistant recruitment on contract basis. Diploma in Engineering required.',
  },
  {
    id: 'jp-013',
    slug: 'civil-services-prelims-2026',
    title: 'Civil Services Examination 2026',
    organization: 'Union Public Service Commission',
    department: 'upsc',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 1100,
    salaryMin: 56100,
    salaryMax: 250000,
    applicationStart: '2026-09-01',
    applicationEnd: '2026-10-20',
    examDate: '2027-01-15',
    status: 'open',
    postedDate: '2026-09-06',
    description: 'Civil Services Examination for IAS, IPS, IFS and other Group A and B services. Graduate in any discipline.',
  },
  {
    id: 'jp-014',
    slug: 'apprentice-fitter-railway',
    title: 'Apprentice Fitter',
    organization: 'Indian Railways',
    department: 'railway',
    qualification: 'iti',
    discipline: 'Fitter Trade',
    state: 'karnataka',
    location: 'Karnataka',
    jobType: 'apprenticeship',
    vacancies: 2500,
    salaryMin: 7000,
    salaryMax: 10000,
    applicationStart: '2026-08-25',
    applicationEnd: '2026-10-10',
    examDate: null,
    status: 'open',
    postedDate: '2026-09-04',
    description: 'Apprentice Fitter recruitment for railway workshops. ITI in Fitter trade required.',
  },
  {
    id: 'jp-015',
    slug: 'assistant-professor-economics',
    title: 'Assistant Professor (Economics)',
    organization: 'State Higher Education Council',
    department: 'teaching',
    qualification: 'post-graduate',
    discipline: 'Economics',
    state: 'kerala',
    location: 'Kerala',
    jobType: 'permanent',
    vacancies: 95,
    salaryMin: 57700,
    salaryMax: 182400,
    applicationStart: '2026-08-28',
    applicationEnd: '2026-09-28',
    examDate: null,
    status: 'open',
    postedDate: '2026-09-03',
    description: 'Assistant Professor recruitment in Economics. Post Graduate with NET/SLET or PhD required.',
  },
  {
    id: 'jp-016',
    slug: 'assistant-engineer-electrical-psu',
    title: 'Assistant Engineer (Electrical)',
    organization: 'National Power Corporation',
    department: 'psu',
    qualification: 'b-e',
    discipline: 'Electrical Engineering',
    state: 'gujarat',
    location: 'Gujarat',
    jobType: 'permanent',
    vacancies: 150,
    salaryMin: 50500,
    salaryMax: 160500,
    applicationStart: '2026-08-15',
    applicationEnd: '2026-09-22',
    examDate: '2026-11-01',
    status: 'closing-soon',
    postedDate: '2026-08-16',
    description: 'Assistant Engineer (Electrical) recruitment for a leading PSU. B.E. in Electrical Engineering required.',
  },
  {
    id: 'jp-017',
    slug: 'sub-inspector-maharashtra-police',
    title: 'Sub-Inspector (Police)',
    organization: 'Maharashtra Police Department',
    department: 'police',
    qualification: 'graduate',
    discipline: 'Any Discipline',
    state: 'maharashtra',
    location: 'Maharashtra',
    jobType: 'permanent',
    vacancies: 800,
    salaryMin: 35400,
    salaryMax: 112400,
    applicationStart: '2026-08-30',
    applicationEnd: '2026-10-12',
    examDate: '2026-12-01',
    status: 'open',
    postedDate: '2026-09-06',
    description: 'Sub-Inspector recruitment for Maharashtra Police. Graduate in any discipline with physical fitness requirements.',
  },
  {
    id: 'jp-018',
    slug: 'software-developer-intern-psu',
    title: 'Software Developer Intern',
    organization: 'National Technology Services',
    department: 'psu',
    qualification: 'b-tech',
    discipline: 'Computer Science / IT',
    state: 'delhi',
    location: 'Delhi',
    jobType: 'internship',
    vacancies: 40,
    salaryMin: 15000,
    salaryMax: 25000,
    applicationStart: '2026-09-01',
    applicationEnd: '2026-09-25',
    examDate: null,
    status: 'open',
    postedDate: '2026-09-05',
    description: 'Software Developer Internship at a government PSU. B.Tech in Computer Science or IT. 6-month internship.',
  },
  {
    id: 'jp-019',
    slug: 'junior-accountant-bihar',
    title: 'Junior Accountant',
    organization: 'Bihar State Finance Department',
    department: 'state-government',
    qualification: 'graduate',
    discipline: 'Commerce / Accounting',
    state: 'bihar',
    location: 'Bihar',
    jobType: 'permanent',
    vacancies: 600,
    salaryMin: 21700,
    salaryMax: 69100,
    applicationStart: '2026-08-12',
    applicationEnd: '2026-08-31',
    examDate: '2026-10-10',
    status: 'closed',
    postedDate: '2026-07-25',
    description: 'Junior Accountant recruitment for Bihar State Finance Department. Graduate in Commerce or Accounting preferred.',
  },
  {
    id: 'jp-020',
    slug: 'forest-ranger-uttarakhand',
    title: 'Forest Ranger',
    organization: 'Uttarakhand Forest Department',
    department: 'state-government',
    qualification: 'graduate',
    discipline: 'Forestry / Environmental Science',
    state: 'uttarakhand',
    location: 'Uttarakhand',
    jobType: 'permanent',
    vacancies: 120,
    salaryMin: 35400,
    salaryMax: 112400,
    applicationStart: '2026-08-05',
    applicationEnd: '2026-08-25',
    examDate: '2026-10-15',
    status: 'closed',
    postedDate: '2026-07-20',
    description: 'Forest Ranger recruitment for Uttarakhand Forest Department. Graduate in Forestry or Environmental Science preferred.',
  },
  {
    id: 'jp-021',
    slug: 'trade-apprentice-bhel',
    title: 'Trade Apprentice (Mechanical)',
    organization: 'Bharat Heavy Engineering Limited',
    department: 'psu',
    qualification: 'iti',
    discipline: 'Mechanical Trade',
    state: 'tamil-nadu',
    location: 'Tamil Nadu',
    jobType: 'apprenticeship',
    vacancies: 350,
    salaryMin: 8000,
    salaryMax: 12000,
    applicationStart: '2026-09-05',
    applicationEnd: '2026-10-20',
    examDate: null,
    status: 'upcoming',
    postedDate: '2026-09-06',
    description: 'Trade Apprentice recruitment in Mechanical trade at BHEL. ITI in relevant trade required. 1-year apprenticeship.',
  },
  {
    id: 'jp-022',
    slug: 'assistant-manager-banking-finance',
    title: 'Assistant Manager (Finance)',
    organization: 'National Banking Services',
    department: 'banking',
    qualification: 'post-graduate',
    discipline: 'Finance / MBA',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 280,
    salaryMin: 64600,
    salaryMax: 144200,
    applicationStart: '2026-08-20',
    applicationEnd: '2026-10-08',
    examDate: '2026-11-25',
    status: 'open',
    postedDate: '2026-09-04',
    description: 'Assistant Manager (Finance) recruitment for participating banks. Post Graduate in Finance or MBA required.',
  },
  {
    id: 'jp-023',
    slug: 'sr-junior-engineer-electrical-railway',
    title: 'Junior Engineer (Electrical)',
    organization: 'Indian Railways',
    department: 'railway',
    qualification: 'diploma',
    discipline: 'Electrical Engineering',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 1800,
    salaryMin: 35400,
    salaryMax: 112400,
    applicationStart: '2026-08-18',
    applicationEnd: '2026-10-01',
    examDate: '2026-12-05',
    status: 'open',
    postedDate: '2026-09-05',
    description: 'Junior Engineer (Electrical) recruitment for various railway zones. Diploma in Electrical Engineering required.',
  },
  {
    id: 'jp-024',
    slug: 'police-constable-tamil-nadu',
    title: 'Police Constable',
    organization: 'Tamil Nadu Police Department',
    department: 'police',
    qualification: '10th-pass',
    discipline: '—',
    state: 'tamil-nadu',
    location: 'Tamil Nadu',
    jobType: 'permanent',
    vacancies: 3200,
    salaryMin: 21700,
    salaryMax: 69100,
    applicationStart: '2026-08-22',
    applicationEnd: '2026-09-18',
    examDate: '2026-11-05',
    status: 'closing-soon',
    postedDate: '2026-08-20',
    description: 'Police Constable recruitment for Tamil Nadu Police. 10th pass with physical fitness requirements.',
  },
  {
    id: 'jp-025',
    slug: 'auditor-accountant-cag',
    title: 'Auditor / Accountant',
    organization: 'Comptroller and Auditor General',
    department: 'ssc',
    qualification: 'graduate',
    discipline: 'Commerce / Accounting',
    state: 'all-india',
    location: 'All India',
    jobType: 'permanent',
    vacancies: 780,
    salaryMin: 25500,
    salaryMax: 81100,
    applicationStart: '2026-09-08',
    applicationEnd: '2026-10-18',
    examDate: null,
    status: 'upcoming',
    postedDate: '2026-09-06',
    description: 'Auditor and Accountant recruitment through SSC for the CAG office. Graduate in Commerce or Accounting preferred.',
  },
];
