import type {
  AdmitCardListing,
  AdmissionListing,
  AnswerKeyListing,
  Category,
  Department,
  ExamListing,
  ExamTool,
  GuideArticle,
  JobListing,
  ResultListing,
} from './types';

export const qualificationCategories: Category[] = [
  { slug: '10th-pass', label: '10th Pass', icon: 'GraduationCap', count: 1240, description: 'Matric-level posts' },
  { slug: '12th-pass', label: '12th Pass', icon: 'BookOpen', count: 980, description: 'Intermediate-level posts' },
  { slug: 'iti', label: 'ITI', icon: 'Wrench', count: 420, description: 'Trade-certified roles' },
  { slug: 'diploma', label: 'Diploma', icon: 'ScrollText', count: 360, description: 'Polytechnic diploma jobs' },
  { slug: 'graduate', label: 'Graduate', icon: 'GraduationCap', count: 2150, description: 'Degree-level opportunities' },
  { slug: 'engineering', label: 'Engineering', icon: 'Cog', count: 780, description: 'B.E. / B.Tech posts' },
  { slug: 'post-graduate', label: 'Post Graduate', icon: 'Award', count: 540, description: 'Master\u2019s and above' },
];

export const allCategories: Category[] = [
  ...qualificationCategories,
  { slug: 'ssc', label: 'SSC', icon: 'FileText', count: 320, description: 'Staff Selection Commission' },
  { slug: 'railway', label: 'Railway', icon: 'TrainFront', count: 610, description: 'Indian Railways' },
  { slug: 'banking', label: 'Banking', icon: 'Landmark', count: 450, description: 'Banking sector jobs' },
  { slug: 'defence', label: 'Defence', icon: 'Shield', count: 290, description: 'Armed forces roles' },
  { slug: 'teaching', label: 'Teaching', icon: 'Users', count: 380, description: 'Teaching & education' },
  { slug: 'police', label: 'Police', icon: 'ShieldCheck', count: 330, description: 'Police & paramilitary' },
  { slug: 'state-government', label: 'State Government', icon: 'Building2', count: 1870, description: 'State-level recruitments' },
];

export const departments: Department[] = [
  { slug: 'ssc', label: 'SSC', icon: 'FileText', count: 320 },
  { slug: 'railway', label: 'Railway', icon: 'TrainFront', count: 610 },
  { slug: 'banking', label: 'Banking', icon: 'Landmark', count: 450 },
  { slug: 'upsc', label: 'UPSC', icon: 'Briefcase', count: 180 },
  { slug: 'defence', label: 'Defence', icon: 'Shield', count: 290 },
  { slug: 'teaching', label: 'Teaching', icon: 'Users', count: 380 },
  { slug: 'police', label: 'Police', icon: 'ShieldCheck', count: 330 },
  { slug: 'psu', label: 'PSU', icon: 'Factory', count: 260 },
  { slug: 'state-government', label: 'State Government', icon: 'Building2', count: 1870 },
];

export const latestJobs: JobListing[] = [
  {
    id: 'job-001',
    title: 'Junior Engineer (Civil)',
    organization: 'Public Works Department',
    category: 'engineering',
    location: 'Multiple States',
    status: 'active',
    posts: 420,
    salary: '\u20b9 35,400 \u2013 \u20b9 1,12,400',
    applicationDeadline: '2026-09-25',
    postedDate: '2026-09-02',
    qualification: 'Diploma / Degree in Civil Engineering',
  },
  {
    id: 'job-002',
    title: 'Assistant Loco Pilot',
    organization: 'Indian Railways',
    category: 'railway',
    location: 'All India',
    status: 'active',
    posts: 9900,
    salary: '\u20b9 19,900 \u2013 \u20b9 63,200',
    applicationDeadline: '2026-09-20',
    postedDate: '2026-09-01',
    qualification: 'ITI / 10th Pass',
  },
  {
    id: 'job-003',
    title: 'Sub-Inspector (Executive)',
    organization: 'Central Armed Police Forces',
    category: 'police',
    location: 'All India',
    status: 'closing-soon',
    posts: 1500,
    salary: '\u20b9 35,400 \u2013 \u20b9 1,12,400',
    applicationDeadline: '2026-09-10',
    postedDate: '2026-08-15',
    qualification: 'Graduate',
  },
  {
    id: 'job-004',
    title: 'Probationary Officer',
    organization: 'National Banking Services',
    category: 'banking',
    location: 'All India',
    status: 'active',
    posts: 3500,
    salary: '\u20b9 23,700 \u2013 \u20b9 42,020',
    applicationDeadline: '2026-10-05',
    postedDate: '2026-09-03',
    qualification: 'Graduate in any discipline',
  },
  {
    id: 'job-005',
    title: 'Primary Teacher',
    organization: 'State Education Board',
    category: 'teaching',
    location: 'State-wide',
    status: 'active',
    posts: 12000,
    salary: '\u20b9 25,500 \u2013 \u20b9 81,100',
    applicationDeadline: '2026-09-30',
    postedDate: '2026-09-04',
    qualification: '12th Pass + D.El.Ed / B.Ed',
  },
  {
    id: 'job-006',
    title: 'Stenographer Grade-C',
    organization: 'Staff Selection Commission',
    category: 'ssc',
    location: 'All India',
    status: 'upcoming',
    posts: 200,
    salary: '\u20b9 25,500 \u2013 \u20b9 81,100',
    applicationDeadline: '2026-10-15',
    postedDate: '2026-09-05',
    qualification: '12th Pass',
  },
];

export const closingSoonJobs: JobListing[] = [
  {
    id: 'cs-001',
    title: 'Sub-Inspector (Executive)',
    organization: 'Central Armed Police Forces',
    category: 'police',
    location: 'All India',
    status: 'closing-soon',
    posts: 1500,
    salary: '\u20b9 35,400 \u2013 \u20b9 1,12,400',
    applicationDeadline: '2026-09-10',
    postedDate: '2026-08-15',
    qualification: 'Graduate',
  },
  {
    id: 'cs-002',
    title: 'Data Entry Operator',
    organization: 'Staff Selection Commission',
    category: 'ssc',
    location: 'All India',
    status: 'closing-soon',
    posts: 850,
    salary: '\u20b9 19,900 \u2013 \u20b9 63,200',
    applicationDeadline: '2026-09-09',
    postedDate: '2026-08-10',
    qualification: '12th Pass',
  },
  {
    id: 'cs-003',
    title: 'Assistant Typist',
    organization: 'State Government Secretariat',
    category: 'state-government',
    location: 'State-wide',
    status: 'closing-soon',
    posts: 320,
    salary: '\u20b9 25,500 \u2013 \u20b9 81,100',
    applicationDeadline: '2026-09-08',
    postedDate: '2026-08-08',
    qualification: 'Graduate with typing skills',
  },
  {
    id: 'cs-004',
    title: 'Constable (GD)',
    organization: 'Central Armed Police Forces',
    category: 'defence',
    location: 'All India',
    status: 'closing-soon',
    posts: 5400,
    salary: '\u20b9 21,700 \u2013 \u20b9 69,100',
    applicationDeadline: '2026-09-12',
    postedDate: '2026-08-12',
    qualification: '10th Pass',
  },
  {
    id: 'cs-005',
    title: 'Technical Assistant',
    organization: 'Public Works Department',
    category: 'diploma',
    location: 'Multiple States',
    status: 'closing-soon',
    posts: 180,
    salary: '\u20b9 25,500 \u2013 \u20b9 81,100',
    applicationDeadline: '2026-09-11',
    postedDate: '2026-08-14',
    qualification: 'Diploma in Engineering',
  },
  {
    id: 'cs-006',
    title: 'Clerk-Cum-Typist',
    organization: 'National Banking Services',
    category: 'banking',
    location: 'All India',
    status: 'closing-soon',
    posts: 1200,
    salary: '\u20b9 19,900 \u2013 \u20b9 63,200',
    applicationDeadline: '2026-09-07',
    postedDate: '2026-08-05',
    qualification: 'Graduate',
  },
];

export const latestResults: ResultListing[] = [
  {
    id: 'res-001',
    title: 'Combined Graduate Level — Tier I',
    organization: 'Staff Selection Commission',
    resultType: 'exam-result',
    status: 'result-out',
    resultDate: '2026-09-05',
  },
  {
    id: 'res-002',
    title: 'Constable (GD) Final Selection',
    organization: 'Central Armed Police Forces',
    resultType: 'final-result',
    status: 'result-out',
    resultDate: '2026-09-03',
  },
  {
    id: 'res-003',
    title: 'Assistant Loco Pilot — CBT 1',
    organization: 'Indian Railways',
    resultType: 'scorecard',
    status: 'result-out',
    resultDate: '2026-08-30',
  },
  {
    id: 'res-004',
    title: 'Probationary Officer — Prelims Merit',
    organization: 'National Banking Services',
    resultType: 'merit-list',
    status: 'upcoming',
    resultDate: '2026-09-15',
  },
  {
    id: 'res-005',
    title: 'Junior Engineer (Civil) — Cutoff Marks',
    organization: 'Public Works Department',
    resultType: 'cutoff',
    status: 'result-out',
    resultDate: '2026-09-01',
  },
];

export const admitCards: AdmitCardListing[] = [
  {
    id: 'ac-001',
    title: 'Junior Engineer (Civil) — Admit Card',
    organization: 'Public Works Department',
    examName: 'JE Civil Written Exam 2026',
    status: 'admit-card-available',
    examDate: '2026-09-18',
    downloadAvailable: true,
  },
  {
    id: 'ac-002',
    title: 'Sub-Inspector (Executive) — Hall Ticket',
    organization: 'Central Armed Police Forces',
    examName: 'CAPF SI Online Exam 2026',
    status: 'admit-card-available',
    examDate: '2026-09-12',
    downloadAvailable: true,
  },
  {
    id: 'ac-003',
    title: 'Probationary Officer — Prelims Admit Card',
    organization: 'National Banking Services',
    examName: 'PO Prelims 2026',
    status: 'upcoming',
    examDate: '2026-09-22',
    downloadAvailable: false,
  },
  {
    id: 'ac-004',
    title: 'Primary Teacher — Written Exam Admit Card',
    organization: 'State Education Board',
    examName: 'Primary Teacher Recruitment Exam',
    status: 'admit-card-available',
    examDate: '2026-09-20',
    downloadAvailable: true,
  },
];

export const upcomingExams: ExamListing[] = [
  {
    id: 'exam-001',
    name: 'Combined Graduate Level (Tier-II)',
    organization: 'Staff Selection Commission',
    category: 'ssc',
    examDate: '2026-09-28',
    applicationDeadline: '2026-08-20',
    applicationStatus: 'closed',
    posts: 7500,
  },
  {
    id: 'exam-002',
    name: 'Probationary Officer — Prelims',
    organization: 'National Banking Services',
    category: 'banking',
    examDate: '2026-09-22',
    applicationDeadline: '2026-08-25',
    applicationStatus: 'closed',
    posts: 3500,
  },
  {
    id: 'exam-003',
    name: 'Junior Engineer (Civil) — Written Exam',
    organization: 'Public Works Department',
    category: 'engineering',
    examDate: '2026-09-18',
    applicationDeadline: '2026-09-25',
    applicationStatus: 'closed',
    posts: 420,
  },
  {
    id: 'exam-004',
    name: 'Stenographer Grade-C — Skill Test',
    organization: 'Staff Selection Commission',
    category: 'ssc',
    examDate: '2026-10-20',
    applicationDeadline: '2026-10-15',
    applicationStatus: 'upcoming',
    posts: 200,
  },
  {
    id: 'exam-005',
    name: 'Primary Teacher — Written Examination',
    organization: 'State Education Board',
    category: 'teaching',
    examDate: '2026-09-20',
    applicationDeadline: '2026-09-30',
    applicationStatus: 'closed',
    posts: 12000,
  },
];

export const answerKeys: AnswerKeyListing[] = [
  {
    id: 'ak-001',
    title: 'Combined Graduate Level (Tier-I) — Provisional Answer Key',
    organization: 'Staff Selection Commission',
    status: 'active',
    releasedDate: '2026-09-02',
  },
  {
    id: 'ak-002',
    title: 'Constable (GD) — Final Answer Key',
    organization: 'Central Armed Police Forces',
    status: 'closed',
    releasedDate: '2026-08-28',
  },
];

export const admissions: AdmissionListing[] = [
  {
    id: 'adm-001',
    institution: 'National Institute of Technology',
    course: 'M.Tech Admission 2026',
    status: 'active',
    applicationDeadline: '2026-09-25',
  },
  {
    id: 'adm-002',
    institution: 'All India Medical Sciences',
    course: 'B.Sc Nursing 2026',
    status: 'active',
    applicationDeadline: '2026-09-18',
  },
];

export const examTools: ExamTool[] = [
  {
    slug: 'age-calculator',
    title: 'Age Calculator',
    description: 'Check if your age meets the eligibility for a post.',
    icon: 'CalendarDays',
  },
  {
    slug: 'percentage-calculator',
    title: 'Percentage Calculator',
    description: 'Convert marks into percentage instantly.',
    icon: 'Calculator',
  },
  {
    slug: 'cgpa-calculator',
    title: 'CGPA Calculator',
    description: 'Convert your CGPA to percentage with one click.',
    icon: 'Percent',
  },
  {
    slug: 'eligibility-checker',
    title: 'Eligibility Checker',
    description: 'Find jobs that match your qualification and age.',
    icon: 'CheckCircle2',
  },
  {
    slug: 'exam-countdown',
    title: 'Exam Countdown',
    description: 'Track days remaining for your upcoming exams.',
    icon: 'Timer',
  },
  {
    slug: 'document-checklist',
    title: 'Document Checklist',
    description: 'Never miss a document when applying for jobs.',
    icon: 'ClipboardList',
  },
];

export const guides: GuideArticle[] = [
  {
    id: 'guide-001',
    title: 'How to Check Your Government Job Eligibility',
    excerpt: 'Understand age limits, qualification requirements, reservation rules and category-based relaxation before you apply.',
    category: 'Getting Started',
    readTime: '5 min read',
    publishedDate: '2026-09-01',
  },
  {
    id: 'guide-002',
    title: 'How to Read a Government Recruitment Notification',
    excerpt: 'Learn to decode every section of a recruitment PDF \u2014 from vacancy breakdown to important dates and fee details.',
    category: 'Guides',
    readTime: '7 min read',
    publishedDate: '2026-08-28',
  },
  {
    id: 'guide-003',
    title: 'Documents Commonly Required for Government Jobs',
    excerpt: 'A complete checklist of certificates, IDs and forms you should keep ready before applying to any sarkari naukri.',
    category: 'Preparation',
    readTime: '6 min read',
    publishedDate: '2026-08-25',
  },
  {
    id: 'guide-004',
    title: 'How to Prepare for Competitive Government Exams',
    excerpt: 'A practical study strategy covering syllabus analysis, mock tests, time management and revision techniques.',
    category: 'Exam Prep',
    readTime: '8 min read',
    publishedDate: '2026-08-20',
  },
];
